config/urls.py
import os
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # Homepage
    path('', include('home.urls')),
    # Admin Area
    path('admin/', admin.site.urls),
    # Templates
    path('products/', include('products.urls')),
    path('profiles/', include('profiles.urls')),
    path('documentation/', include('documentation.urls')),
    # APIs
    path('api/', include('products.api.urls'))
]


urlpatterns += [
    path('accounts/', include('accounts.urls')),
    # User Authentication
    path('accounts/', include('django.contrib.auth.urls')),
    # Login: /accounts/login/
    # Logout: /accounts/logout/
    # Password Change: /accounts/password_change/
    # Password Change Done: /accounts/password_change/done/
    # Password Reset: /accounts/password_reset/
    # Password Reset Done: /accounts/password_reset/done/
    # Password Reset Confirm: /accounts/reset/<uidb64>/<token>/
    # Password Reset Complete: /accounts/reset/done/

]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.BASE_DIR / 'static')
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from .views import homepage

urlpatterns = [
    path('', homepage, name='homepage'),
]

products/urls.py
from django.urls import path
from .views import ProductListView, ProductDetailView

app_name = 'products'

urlpatterns = [
    path('', ProductListView.as_view(), name='products-list'),
    path('<int:pk>/', ProductDetailView.as_view(), name='products-detail'),
]

profiles/models/athletes.py
from django.db import models


class Athlete(models.Model):
    """Model representing an athlete."""
    first_name = models.CharField(max_length=100, verbose_name="Nome")
    last_name = models.CharField(max_length=100, verbose_name="Cognome")
    date_of_birth = models.DateField(verbose_name="Data di Nascita")
    place_of_birth = models.CharField(max_length=150, verbose_name="Luogo di Nascita")
    fiscal_code = models.CharField(max_length=16, unique=True, verbose_name="Codice Fiscale")
    category = models.ForeignKey(
        "Category",
        on_delete=models.PROTECT,
        verbose_name="Categoria",
        related_name="athletes"
    )

    trainer = models.ForeignKey(
        "Trainer",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        verbose_name="Trainer",
        related_name="athletes"
    )

    class Meta:
        verbose_name = "Atleta"
        verbose_name_plural = "Atleti"
        # ordering = ["last_name", "first_name"]

    def __str__(self):
        return f"{self.first_name} {self.last_name} ({self.fiscal_code})"

    def __repr__(self):
        return (f"Athlete(first_name={self.first_name}, last_name={self.last_name}, "
                f"date_of_birth={self.date_of_birth}, fiscal_code={self.fiscal_code})")


class Category(models.Model):
    code = models.CharField(max_length=4, unique=True)
    description = models.CharField(max_length=50)
    age_range = models.CharField(max_length=20, blank=True, null=True)

    class Meta:
        verbose_name = "Categoria"
        verbose_name_plural = "Categorie"
        # ordering = ["code"]

    def __str__(self):
        return f"{self.code} - {self.description}"

    def __repr__(self):
        return f"Category(code={self.code}, description={self.description}, age_range={self.age_range})"

templates/includes/navbar.html
{% load static %}

<nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-1">
  <div class="container-fluid">
    <!-- Brand -->
    <a class="navbar-brand" href="/">
      <img src="{% static 'img/logo.jpg' %}" alt="ASD-Logo" width="100" height="auto"
           class="d-inline-block align-text-top">
    </a>

    <!-- Toggler Button -->
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo02"
            aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <!-- Navbar Links -->
    <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
        {% if user.is_authenticated %}
        {% if user.is_staff or user.is_superuser %}
        <!-- Temporary -->
        <!-- Dropdown Athletes Handler -->
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#"
             id="athletes-handler"
             role="button" data-bs-toggle="dropdown" aria-expanded="false"
          > Gestione Atleti
          </a>
          <ul class="dropdown-menu" aria-labelledby="athletes-handler">
            <li><a class="dropdown-item" href="{% url 'athlete_list' %}">Elenco Atleti</a></li>
            <li><a class="dropdown-item" href="{% url 'athlete_create' %}">Inserisci Nuovo Atleta</a></li>
          </ul>
        </li>

        <!-- Temporary -->
        <!-- Dropdown Trainers Handler -->
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#"
             id="trainers-handler"
             role="button" data-bs-toggle="dropdown" aria-expanded="false"
          > Gestione Tecnici
          </a>
          <ul class="dropdown-menu" aria-labelledby="trainers-handler">
            <li><a class="dropdown-item" href="{% url 'trainer_list' %}">Elenco Tecnici</a></li>
            <li><a class="dropdown-item" href="{% url 'trainer_create' %}">Inserisci Nuovo Tecnico</a></li>
          </ul>
        </li>

        <!-- Temporary -->
        <!-- Dropdown Doctors Handler -->
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#"
             id="doctors-handler"
             role="button" data-bs-toggle="dropdown" aria-expanded="false"
          > Gestione Medici
          </a>
          <ul class="dropdown-menu" aria-labelledby="doctors-handler">
            <li><a class="dropdown-item" href="{% url 'sport_doctor_list' %}">Elenco Medici</a></li>
            <li><a class="dropdown-item" href="{% url 'sport_doctor_create' %}">Inserisci Nuovo Medico</a>
            </li>
          </ul>
        </li>

        <!-- Temporary -->
        <!-- Dropdown Documentation -->

        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#"
             id="documentation-handler"
             role="button" data-bs-toggle="dropdown" aria-expanded="false"
          > Documentazione
          </a>
          <ul class="dropdown-menu" aria-labelledby="documentation-handler">
            <li><a class="dropdown-item" href="{% url 'sport_certificate_list' %}">Elenco Certificati
              Medici</a></li>
            <li><a class="dropdown-item" href="{% url 'sport_certificate_create' %}">Inserisci Nuovo
              Certificato Medico</a></li>
          </ul>
        </li>
        {% endif %}
        {% endif %}


        <!-- Dropdown Authentication -->
        <li class="nav-item dropdown">
          <a
                  class="nav-link dropdown-toggle"
                  href="#"
                  id="authentication-dropdown"
                  role="button"
                  data-bs-toggle="dropdown"
                  aria-expanded="false"
          >
            {% if user.is_authenticated %}
            👤 {{ user.username }}
            {% else %}
            🔑 Autenticazione
            {% endif %}
          </a>
          <ul class="dropdown-menu" aria-labelledby="authentication-dropdown">
            {% if user.is_authenticated %}
            <li>
              <a class="dropdown-item" href="#">
                📋 Visualizza Profilo
              </a>
            </li>
            <li>
              <a class="dropdown-item" href="{% url 'password_change' %}">
                🔑 Cambia Password
            </a>
        </li>
            <li>
              <form method="post" action="{% url 'logout' %}">
                {% csrf_token %}
                <button type="submit" class="dropdown-item">
                  🚪 Esci
                </button>
              </form>
            </li>
            {% if user.is_superuser %}
            <li>
              <hr class="dropdown-divider">
            </li>
            <li>
              <a class="dropdown-item" href="/admin/">
                ⚙️ Admin Area
              </a>
            </li>
            {% endif %}
            {% else %}
            <li>
              <a class="dropdown-item" href="{% url 'login' %}">
                🔓 Accedi
              </a>
            </li>
            <li>
              <a class="dropdown-item" href="{% url 'signup' %}">
                📝 Registrati
              </a>
            </li>
            {% endif %}
          </ul>
        </li>


        <!-- Temporary -->
        <!--
        <li class="nav-item dropdown me-2">
          <a class="nav-link dropdown-toggle active" href="#" id="sportwig" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Sportwig
          </a>
          <ul class="dropdown-menu" aria-labelledby="sportwig">
            <li><a class="dropdown-item" href="{% url 'products:products-list' %}">Lista Servizi</a></li>
            <li><a class="dropdown-item" href="{% url 'products-api-list' %}">API - Lista Servizi</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#}">Logout</a></li>
          </ul>
        </li>
        -->
        <!-- Dropdown Gestione Operatori -->
        <!--
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="gestioneOperatoriDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Gestione Operatori
          </a>
          <ul class="dropdown-menu" aria-labelledby="gestioneOperatoriDropdown">
            <li><a class="dropdown-item" href="#">Gestione Servizi</a></li>
            <li><a class="dropdown-item" href="#">Gestione Documentazione</a></li>
            <li><a class="dropdown-item" href="#">Gestione Anagrafiche</a></li>
            <li><a class="dropdown-item" href="#">Gestione Bandi</a></li>
            <li><a class="dropdown-item" href="#">Gestione Profilo</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#}">Logout</a></li>
          </ul>
        </li>
        -->
        <!-- Dropdown Gestione Utente -->
        <!--
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="gestioneUtenteDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Gestione Utente
          </a>
          <ul class="dropdown-menu" aria-labelledby="gestioneUtenteDropdown">
            <li><a class="dropdown-item" href="#">Gestione Atleti</a></li>
            <li><a class="dropdown-item" href="#">Servizi ASD</a></li>
            <li><a class="dropdown-item" href="#">Gestione Profilo</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#}">Logout</a></li>
          </ul>
        </li>
        -->

        <!-- Dropdown Admin -->
        <!--
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="profiloDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Admin
          </a>
          <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="profiloDropdown">
            <li><a class="dropdown-item" href="#">Gestione Operatori</a></li>
            <li><a class="dropdown-item" href="#">Gestione Utenti</a></li>
            <li><a class="dropdown-item" href="#">Gestione Profilo</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#}">Logout</a></li>
          </ul>
        </li>
        -->
      </ul>
    </div>
  </div>
</nav>