config/urls.py
import os
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # Homepage
    path('', include('home.urls')),
    # Admin Area
    path('admin/', admin.site.urls),
    # Templates
    path('products/', include('products.urls')),
    path('profiles/', include('profiles.urls')),
    path('documentation/', include('documentation.urls')),
    # APIs
    path('api/', include('products.api.urls'))
]


urlpatterns += [
    path('accounts/', include('accounts.urls')),
    # User Authentication
    path('accounts/', include('django.contrib.auth.urls')),
    # Login: /accounts/login/
    # Logout: /accounts/logout/
    # Password Change: /accounts/password_change/
    # Password Change Done: /accounts/password_change/done/
    # Password Reset: /accounts/password_reset/
    # Password Reset Done: /accounts/password_reset/done/
    # Password Reset Confirm: /accounts/reset/<uidb64>/<token>/
    # Password Reset Complete: /accounts/reset/done/

]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.BASE_DIR / 'static')
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from .views import homepage

urlpatterns = [
    path('', homepage, name='homepage'),
]

products/api/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import ProductViewSet

router = DefaultRouter()
router.register(r'products', ProductViewSet, basename='products-api')

urlpatterns = [
    path('', include(router.urls)),
]

products/urls.py
from django.urls import path
from .views import ProductListView, ProductDetailView

app_name = 'products'

urlpatterns = [
    path('', ProductListView.as_view(), name='products-list'),
    path('<int:pk>/', ProductDetailView.as_view(), name='products-detail'),
]

products/models.py
from django.db import models


class Product(models.Model):
    description = models.TextField(max_length=150)
    price = models.FloatField()
    available = models.BooleanField(default=True)
    image = models.ImageField(upload_to='products/', null=True, blank=True)

    class Meta:
        verbose_name = 'Prodotto'
        verbose_name_plural = 'Prodotti'

    def __str__(self):
        return self.description

products/api/views.py
from rest_framework import viewsets
from products.models import Product
from products.api.serializers import ProductSerializer
from config.permissions import IsAdminOrReadOnly


class ProductViewSet(viewsets.ModelViewSet):
    permission_classes = [IsAdminOrReadOnly]
    queryset = Product.objects.all().order_by('price')
    serializer_class = ProductSerializer
    # renderer_classes = [CustomBrowsableAPIRenderer, JSONRenderer]

products/views.py
from django.views.generic import ListView, DetailView
from .models import Product


class ProductListView(ListView):
    """ Show all products """
    model = Product
    template_name = 'products/products_list.html'
    context_object_name = 'products'
    ordering = ['price']


class ProductDetailView(DetailView):
    """ Show product details """
    model = Product
    template_name = 'products/products_detail.html'
    context_object_name = 'product'

products/templates/products/product_detail.html
{% extends 'base.html' %}

{% block title %}{{block.super}} - Dettaglio Prodotto{% endblock %}

{% block content %}

<html>
    <head>
        <title>{{ product.description }}</title>
    </head>
    <body>
        <h1>{{ product.description }}</h1>
        <p>Prezzo: €{{ product.price }}</p>
        <p>Disponibile: {{ product.available|yesno:"Sì,No" }}</p>
        <a href="{% url 'products:product-list' %}">Torna alla lista prodotti</a>
    </body>
</html>

{% endblock %}

products/templates/products/products_detail.html
{% extends 'base.html' %}

{% block title %}{{block.super}} - Dettaglio Prodotto{% endblock %}

{% block content %}

<html>
    <head>
        <title>{{ product.description }}</title>
    </head>
    <body>
        <h1>{{ product.description }}</h1>
        <p>Prezzo: €{{ product.price }}</p>
        <p>Disponibile: {{ product.available|yesno:"Sì,No" }}</p>
        <a href="{% url 'products:products-list' %}">Torna alla lista prodotti</a>
    </body>
</html>

{% endblock %}

products/templates/products/products_list.html
<!--{% extends 'base.html' %}-->

<!--{% block title %}{{block.super}} - Lista Prodotti{% endblock %}-->

<!--{% block content %}-->

<!--<html>-->

<!--    <head>-->
<!--        <title>Lista Prodotti</title>-->
<!--    </head>-->
<!--    <body>-->
<!--        <div class="row row-cols-1 row-cols-md-3 g-4">-->
<!--            {% for product in products %}-->
<!--                <div class="col">-->
<!--                    <div class="card h-100">-->
<!--                        <img src="{{ product.image.url }}" class="card-img-top" alt="{{ product.description }}">-->
<!--                        <div class="card-body">-->
<!--                            <h5 class="card-title">{{ product.description }}</h5>-->
<!--                            <p class="card-text">Prezzo: € {{ product.price | floatformat:2 }}</p>-->
<!--                        </div>-->
<!--                        <div class="card-footer d-flex justify-content-between">-->
<!--                            <a href="{% url 'products:products-detail' product.pk %}">-->
<!--                            &lt;!&ndash; Modal Button Optionally &ndash;&gt;-->
<!--                            <button type="button" class="btn btn-primary">-->
<!--                            Vai al Prodotto-->
<!--                            </button>-->
<!--                            </a>-->
<!--                        </div>-->
<!--                    </div>-->
<!--                </div>-->
<!--            {% empty %}-->
<!--                <li>Nessun prodotto disponibile.</li>-->
<!--            {% endfor %}-->
<!--        </div>-->
<!--    </body>-->
<!--</html>-->

<!--{% endblock %}-->